# Generated by Django 5.0.2 on 2024-03-21 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(blank=True, default='15blue.jpeg', upload_to='images/')),
                ('img_2', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikname', models.CharField(max_length=50)),
                ('rev', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VidTovara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование товара')),
                ('memory', models.CharField(default='256gb', max_length=20, verbose_name='Объем памяти')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Цвет')),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение товара')),
                ('slug', models.SlugField(blank=True)),
                ('promo', models.ManyToManyField(blank=True, related_name='promo', to='iphone.promo', verbose_name='Акции')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vid', to='iphone.vidtovara', verbose_name='Вид товара')),
            ],
            options={
                'verbose_name': 'Товар магазина',
                'verbose_name_plural': 'Товары магазина',
            },
        ),
    ]
