# Generated by Django 5.0.2 on 2024-03-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
