# Generated by Django 5.0.2 on 2024-03-27 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphone', '0003_iphone_descrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone',
            name='rev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='iphone.review'),
        ),
    ]
