# Generated by Django 5.0.2 on 2024-03-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iphone', '0004_iphone_rev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iphone',
            name='rev',
        ),
    ]
