# Generated by Django 5.0.2 on 2024-03-27 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphone', '0005_remove_iphone_rev'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='iphone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='iphone.iphone'),
        ),
    ]
